//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02_Connections_Football_DB_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Stadium { get; set; }
        public string Score { get; set; }
        public int Team1_Id { get; set; }
        public int Team2_Id { get; set; }
        public int Referee_Id { get; set; }
    
        public virtual Referee Referee { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
