
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace _03_Data_Annotations_Testing
{
    // ComplexType - indicates that this class will not be considered as a separate table,
    // but instead its properties will be included in parent table
    [ComplexType]
    public class ContactInfo
    {
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
    }

    [Table("Active Users")]
    public class User
    {
        // key - sets the property as a primary key
        // DatabaseGenerated(DatabaseGeneratedOption.Identity) - makes it auto generated by db
        // If the type of the key is int, then the second attribute is not necessary
        [Key,DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int IdentNumber { get; set; }

        // Required - makes the column NOT NULL in db
        // MinLength and MaxLength - sets the minimum and maximum lengths of string data
        [Required,MinLength(2),MaxLength(20)]
        public string Name { get; set; }

        // NotMapped - does not include the mentioned property in the table
        [NotMapped]
        public bool IsInvalid { get; set; }

        // To set custom table or column names
        // Table("Table_Name")
        // Column("Col_Name")
        [Column("Last Name")]
        public string Surname { get; set; }

        // ForeignKey("FK_Name") - to set a foreign key        
        public int? Company_Id { get; set; }
        [ForeignKey("Company_Id")]
        public Company Company { get; set; }

        // the properties of Contacts will be joined to this table,
        // because it is a ComplexType
        public ContactInfo Contacts { get; set; }
    }
}
